project:
  type: book

book:
  title: "Previsão de Séries temporais com Python: um pequeno guia"
  author: "Felipe Angelim"
  date: "10/11/2025"
  favicon: "logo.jpeg"
  search: true
  repo-url: https://github.com/sktime/python_brasil_2025/
  sharing: [twitter, facebook]
  cover-image: "logo.jpeg"
  cover-image-alt: "Uma ilustração de séries temporais"
  chapters:
  - index.qmd
  - part: "Part I: Básico"
    chapters:
      - content/pt/part1/00_intro.qmd
      - content/pt/part1/01_naive.qmd
      - content/pt/part1/02_components_and_diff.qmd
      - content/pt/part1/03_ets_and_ar.qmd
      - content/pt/part1/04_metricas.qmd
  - part: "Part II: Intermediário"
    chapters:
      - content/pt/part2/01_exog_variables.qmd
      - content/pt/part2/02_ml_models.qmd
      - content/pt/part2/03_panel_data.qmd
      - content/pt/part2/04_hierarchical_forecasting.qmd
      - content/pt/part2/05_deep_learning.qmd
  - part: "Part III: Apêndices"
    chapters:
      - content/pt/extra/sktime_custom.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



